# Generated by Django 5.1.7 on 2025-03-22 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('current_level', models.CharField(blank=True, max_length=50, null=True)),
                ('target_level', models.TextField(blank=True, null=True)),
                ('total_score', models.IntegerField(blank=True, null=True)),
                ('target_study_time', models.FloatField(blank=True, help_text='目標学習時間 (h)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningMainTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_topic', models.CharField(max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('incomplete', '未完了'), ('completed', '完了')], default='incomplete')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('learning_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.learningobjective')),
            ],
        ),
        migrations.CreateModel(
            name='LearningSubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_topic', models.CharField(max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('estimated_time', models.FloatField(blank=True, help_text='推定学習時間 (h)', null=True)),
                ('status', models.CharField(choices=[('incomplete', '未完了'), ('completed', '完了')], default='incomplete')),
                ('main_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_topics', to='task_manager.learningmaintopic')),
            ],
        ),
        migrations.CreateModel(
            name='UserInterestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'category')},
            },
        ),
    ]
